---
app:
  timezone: UTC # server timezone
  repo: git@github.com:DigitalPolice/citydepartment.git # blessed repository
  build_root: /home/vagrant/police/ # where we will be building the application before deploy
  env: dev # or prod
  host: police.local # the hostname where the system will be served
  root: /vagrant # where the application has to be deployed (or is already deployed)
  version: master # what branch to use for building
  mysql_root_password: iKRCE81Tnw67a4jY
  rsync_opts: '--exclude .git --exclude app/cache --exclude app/logs'

  # Configuration below is provided for generation of parameters.yml file when building app
  db:
    driver: pdo_mysql
    host: localhost
    port: ~
    name: police
    user: police
    pass: p0l1c3&th1ev3s

  mailer:
    transport: smtp
    host: 127.0.0.1
    port: ~
    user: ~
    pass: ~

  secret: ZiQRdn6k5rA4XU88

server:
  install: '1'
  packages: [git]
  locale: en_US.UTF-8
vagrant_local:
  install: '1'
  vm:
    base_box: trusty64
    hostname: police.local
    ip: 10.10.10.8
    memory: '1024'
    sharedfolder: ./
    useVagrantCloud: '1'
    syncType: nfs
php:
  install: '1'
  packages: [php7.0-fpm, php7.0-cli, php7.0-intl, php7.0-mcrypt, php7.0-curl, php7.0-mysql, php7.0-sqlite3]
  fpm:
    listen: /var/run/php/php7.0-fpm.sock

# Percona configuration
# This configuration is optimal for vagrant box. When working on staging or production we will require adequate values.
bind_address: 0.0.0.0
max_allowed_packet: 16M
key_buffer: 16M
thread_stack: 192K
thread_cache_size: 8

# Nginx configuration
# Again, this configuration is optimal for vagrant box or single webserver. When working on staging and production
# please use adequate values.
nginx_extra_http_options: |
  proxy_buffering    off;
  proxy_set_header   X-Real-IP $remote_addr;
  proxy_set_header   X-Scheme $scheme;
  proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header   Host $http_host;

nginx_remove_default_vhost: true
