---
- name: Add php7.0 ppa
  apt_repository: repo=ppa:ondrej/php update_cache=yes
  environment:
    LC_ALL: en_US.UTF-8

- name: Update apt
  become: true
  apt: update_cache=yes

- name: Install PHP Packages
  become: true
  apt: pkg={{ item }} state=latest
  with_items: php.packages
  when: php.packages is defined

- include: configure.yml
- include: composer.yml
