---
- name: Create dir for clone
  local_action: file dest=~/police
                state=directory

- name: Checkout the deployment branch
  local_action: git repo={{ app.repo }}
                dest={{ app.build_root }}
                version={{ app.version }}
                accept_hostkey=yes

- name: Clean up from previous builds
  local_action: command git clean -df .
  args:
    chdir: "{{ app.build_root }}"

- name: Generate parameters.yml file
  local_action: template
                src=parameters.yml
                dest="{{ app.build_root }}/app/config/parameters.yml"
                mode=0644

- name: Run composer install
  local_action: shell ./composer.sh install --optimize-autoloader --no-interaction
  args:
    chdir: "{{ app.build_root }}"
  environment:
    SYMFONY_ENV: "{{ app.env }}"

- name: Install assets
  local_action: command ./app/console assets:install
  args:
    chdir: "{{ app.build_root }}"
  environment:
    SYMFONY_ENV: "{{ app.env }}"

- name: Dump assets
  local_action: command ./app/console assetic:dump
  args:
    chdir: ~/police
  environment:
    SYMFONY_ENV: "{{ app.env }}"
