---
- name: Create the directory for the code
  file: dest={{ app.root }}
        state=directory
        owner=root group=root mode=0755

- name: Upload the build to the server
  local_action: command rsync -a --delete {{ app.rsync_opts }} {{ app.build_root }} {{ ansible_ssh_user }}@{{ inventory_hostname }}:{{ app.root }}
  notify:
     - restart nginx
     - restart php5-fpm

- name: Setup file permissions
  file: dest={{ item }} owner="www-data" group="www-data" mode=0755 recurse=yes state=directory
  with_items:
    - "{{ app.root }}/app/cache"
    - "{{ app.root }}/app/logs"
    - "{{ app.root }}/app/tmp"

- name: Clean cache
  become: yes
  become_user: www-data
  command: ./app/console cache:clear
  args:
    chdir: "{{ app.root }}"
  environment:
    SYMFONY_ENV: "{{ app.env }}"

- name: Create the database if needed
  become: yes
  become_user: www-data
  command: ./app/console doctrine:database:create --if-not-exists --no-interaction
  args:
    chdir: "{{ app.root }}"
  environment:
    SYMFONY_ENV: "{{ app.env }}"

- name: Update the database
  become: yes
  become_user: www-data
  command: ./app/console doctrine:schema:update --force --no-interaction
  args:
    chdir: "{{ app.root }}"
  environment:
    SYMFONY_ENV: "{{ app.env }}"

- name: Install fixtures
  become: yes
  become_user: www-data
  command: ./app/console doctrine:fixtures:load --no-interaction
  args:
    chdir: "{{ app.root }}"
  environment:
    SYMFONY_ENV: "{{ app.env }}"
  when: app.env == 'dev'
