---
- name: install git
  become: true
  apt: package=git state=latest
  tags:
    - vagrant

- name: Set the hostname in /etc/hostname
  become: true
  shell: echo {{ vagrant_local.vm.hostname }} > /etc/hostname
  when: app.host is defined
  tags:
    - vagrant

- name: Set the hostname
  become: true
  shell: hostname {{ app.host }}
  when: app.host is defined
  tags:
      - vagrant

- name: Update /etc/hosts
  become: true
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost {{ app.host }}' owner=root group=root mode=0644
  when: app.host is defined
  tags:
    - vagrant

- name: Install xdebug.
  become: true
  apt: package=php-xdebug state=latest
  tags:
    - vagrant

- name: Unlink xdebug configuration (fpm, cli)
  become: true
  file: >
    dest={{ item }}
    state=absent
  with_items:
    - /etc/php/7.0/fpm/conf.d/20-xdebug.ini
    - /etc/php/7.0/cli/conf.d/20-xdebug.ini

- name: Configure xdebug for fpm
  become: true
  template: >
    src=xdebug.fpm.ini
    dest=/etc/php/7.0/fpm/conf.d/20-xdebug.ini
    owner="root" group="root" mode=0644
  notify:
    - restart php7-fpm
  tags:
    - vagrant

- name: Disable xdebug for cli scripts.
  become: true
  template: >
    src=xdebug.cli.ini
    dest=/etc/php/7.0/cli/conf.d/20-xdebug.ini
    owner="root" group="root" mode=0644
  tags:
    - vagrant

- name: Create aliases for php.
  lineinfile: >
    line="alias php='php -dzend_extension=xdebug.so'"
    dest=/home/vagrant/.bashrc
  tags:
    - vagrant

- name: Create alias for phpunit.
  lineinfile: >
      line="alias phpunit='php $(which phpunit)'"
      dest=/home/vagrant/.bashrc
  tags:
    - vagrant

- name: Add XDEBUG_CONFIG environment variable
  lineinfile: >
      line='export XDEBUG_CONFIG="idekey=vagrant"'
      dest=/home/vagrant/.bashrc
  tags:
    - vagrant
